# Generated by Django 4.2 on 2023-05-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='task',
        ),
    ]
