# Generated by Django 4.2 on 2023-05-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_data_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.TextField(),
        ),
    ]
